/*
 *     ____             _________                __                _     
 *    / __ \___  ____ _/ /_  __(_)___ ___  ___  / /   ____  ____ _(_)____
 *   / /_/ / _ \/ __ `/ / / / / / __ `__ \/ _ \/ /   / __ \/ __ `/ / ___/
 *  / _, _/  __/ /_/ / / / / / / / / / / /  __/ /___/ /_/ / /_/ / / /__  
 * /_/ |_|\___/\__,_/_/ /_/ /_/_/ /_/ /_/\___/_____/\____/\__, /_/\___/  
 *                                                       /____/          
 *
 *                  Barracuda Embedded Web-Server
 *
 ****************************************************************************
 *			      HEADER
 *
 *   $Id: IoIntfCspReader.h 5978 2026-09-11 16:13:48Z wini $
 *
 *   COPYRIGHT:  Real Time Logic LLC, 2008
 *
 *   This software is copyrighted by and is the sole property of Real
 *   Time Logic LLC.  All rights, title, ownership, or other interests in
 *   the software remain the property of Real Time Logic LLC.  This
 *   software may only be used in accordance with the terms and
 *   conditions stipulated in the corresponding license agreement under
 *   which the software has been supplied.  Any unauthorized use,
 *   duplication, transmission, distribution, or disclosure of this
 *   software is expressly forbidden.
 *                                                                        
 *   This Copyright notice may not be removed or modified without prior
 *   written consent of Real Time Logic LLC.
 *                                                                         
 *   Real Time Logic LLC. reserves the right to modify this software
 *   without notice.
 *
 *               http://www.realtimelogic.com
 ****************************************************************************
 *
 *
 */
/** @file IoIntfCspReader.h */

#ifndef __IoIntfCspReader_h
#define __IoIntfCspReader_h

#include <CspRunTm.h>
#include <IoIntf.h>

/** The IoIntfCspReader, which implements the abstract CspReader
    interface, makes it possible to open a "CSP dat" file via a IoIntf.
@ingroup IO
 */
typedef struct IoIntfCspReader
#ifdef __cplusplus
: public CspReader
{
      /** Uninitialized storage; initialize before use or destruction. */
      IoIntfCspReader() {}

   /** The IoIntfCspReader constructor opens the CSP data file for reading.
       \param io Borrowed seekable I/O interface, valid until this reader closes.
       \param pathName Required NUL-terminated path within io to the data file
       generated by httpLink; used during construction only.
       Check inherited CspReader::isValid before use. A stat/open failure leaves
       the reader invalid. Debug builds call baFatalE if the initial magic
       number cannot be read or does not match the CSP data format. 
   */
   IoIntfCspReader(IoIntf* io, const char* pathName);
      
   /** Close an open file, ignoring the close status.
       Stop all users of this reader before destruction.
    */
   ~IoIntfCspReader();

   /** Close and consume the file handle, even if closing fails.
       Stop all reads first. The inherited isValid flag is not cleared; never
       use it to decide whether reading after close is safe.
       @return Zero on success, the underlying negative close error, or -1
       if the file is not open.
    */
    int close();

   private:
#else
{
   CspReader reader;
#endif
      U32 currentOffset;
      IoIntf_SeekAndRead seekAndReadFp;
      ResIntfPtr fp;
} IoIntfCspReader;

#ifdef __cplusplus
extern "C" {
#endif
/** Initialize a CSP data reader; see IoIntfCspReader::IoIntfCspReader.
 * @param[out] o Caller-owned object to initialize.
 * @param[in] io Borrowed seekable I/O interface, valid until close.
 * @param[in] pathName Required NUL-terminated CSP data path within io.
 * Check CspReader_isValid before use. */
BA_API void IoIntfCspReader_constructor(IoIntfCspReader* o,
                                        IoIntf* io,
                                        const char* pathName);
/** Close the reader after all its users have stopped.
 * @param[in,out] o Initialized reader; no further reads are allowed.
 * @return Zero success, underlying negative close error, or -1 if not open.
 * See IoIntfCspReader::close. */
BA_API int IoIntfCspReader_close(IoIntfCspReader* o);
/** Close without freeing the object itself.
 * @param[in,out] o Initialized reader whose users have stopped.
 * The C++ destructor discards the close status. */
#define IoIntfCspReader_destructor(o) IoIntfCspReader_close(o);
#ifdef __cplusplus
}
inline IoIntfCspReader::IoIntfCspReader(IoIntf* io, const char* pathName) {
   IoIntfCspReader_constructor(this, io, pathName); }
inline IoIntfCspReader::~IoIntfCspReader() {
   IoIntfCspReader_destructor(this); }
inline int IoIntfCspReader::close() {
   return IoIntfCspReader_close(this); }
#endif


#endif
