
# Program to test the REST API
# Generated by chatGPT

BASE_URL = "http://localhost/api/users"

import requests

def print_response(r):
    print(f"Status: {r.status_code}")
    print("Response:", r.text)
    print("-" * 40)

def post_user(name, email):
    return requests.post(BASE_URL, json={"name": name, "email": email})

print("Creating 5 users:")
for i in range(5):
    r = post_user(f"User{i+1}", f"user{i+1}@example.com")
    print_response(r)

print("Fetching all users:")
r = requests.get(BASE_URL)
print_response(r)

print("Fetching user with id=1:")
print_response(requests.get(f"{BASE_URL}/1"))

print("Fetching non-existent user with id=99:")
print_response(requests.get(f"{BASE_URL}/99"))

print("Testing POST with missing 'email':")
bad_user = {"name": "BadUser"}
print_response(requests.post(BASE_URL, json=bad_user))

print("Creating 6 more users to test DB full condition:")
for i in range(6):
    r = post_user(f"ExtraUser{i+1}", f"extrauser{i+1}@example.com")
    print_response(r)

# Delete every second user: 1, 3, 5, 7, 9
print("Deleting every second user (1, 3, 5, 7, 9):")
for i in range(1, 11, 2):
    r = requests.delete(f"{BASE_URL}/{i}")
    print(f"DELETE /users/{i}")
    print_response(r)

# Try adding 5 new users again
print("Adding 5 new users after deletions:")
for i in range(5):
    r = post_user(f"NewUser{i+1}", f"newuser{i+1}@example.com")
    print_response(r)
